import './game-data'
import './function/templating'
import './function/templateItem'
import './function/gameFunctions'
import './render'
import './blocks'
import './screen/start'
import './screen/game'
import './css/style.css'

